version: "3.9"

services:
  backend:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.api
    container_name: indus_guardian_api
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      # This maps your local code: Change code -> Container updates instantly
      - ../backend:/app/backend
      - indus_guardian_data:/app/backend/data
      - indus_guardian_logs:/app/backend/logs
    networks:
      - indus_network

  frontend:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.ui
    container_name: indus_guardian_ui
    depends_on:
      - backend
    ports:
      - "8501:8501"
    restart: unless-stopped
    volumes:
      # This maps your local frontend code
      - ../frontend:/app/frontend
    networks:
      - indus_network

volumes:
  indus_guardian_data:
  indus_guardian_logs:

networks:
  indus_network: